# Generated by Django 4.2.27 on 2026-02-03 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=50000.0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('asset_id', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='trading.portfolio')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['asset_id', '-timestamp'], name='trading_pri_asset_i_d68edd_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('alert', 'Alert'), ('system', 'System')], max_length=10)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='trading.portfolio')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TradingStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=10)),
                ('strategy_type', models.CharField(choices=[('threshold', 'Threshold'), ('trailing', 'Trailing Stop'), ('dca', 'Dollar Cost Averaging')], default='threshold', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('buy_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('sell_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('trade_amount', models.DecimalField(decimal_places=8, default=0.01, max_digits=20)),
                ('trailing_percent', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('highest_price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('lowest_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('trailing_stop_price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('trailing_buy_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('dca_interval', models.IntegerField(default=60)),
                ('dca_amount', models.DecimalField(decimal_places=2, default=100, max_digits=20)),
                ('last_dca_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to='trading.portfolio')),
            ],
            options={
                'unique_together': {('portfolio', 'asset_id')},
            },
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('average_cost', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='trading.portfolio')),
            ],
            options={
                'unique_together': {('portfolio', 'asset_id')},
            },
        ),
    ]
